# Generated by Django 6.1 on 2026-08-31 13:56

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsageReservation",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_token", models.CharField(max_length=128)),
                ("bytes", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("whitelist", "Whitelist"), ("blacklist", "Blacklist")],
                        max_length=16,
                    ),
                ),
                ("subject_type", models.CharField(max_length=16)),
                ("subject_value", models.CharField(max_length=128)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_by_id", models.CharField(blank=True, max_length=64)),
                ("created_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "access_rules",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "subject_type", "subject_value"), name="unique_access_rule"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyUsage",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("identifier", models.CharField(max_length=64)),
                ("identifier_type", models.CharField(max_length=16)),
                ("day", models.DateField()),
                ("charged_bytes", models.PositiveBigIntegerField(default=0)),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("active_tasks", models.PositiveIntegerField(default=0)),
                (
                    "reservations",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        default=list, embedded_model="usage.usagereservation"
                    ),
                ),
            ],
            options={
                "db_table": "daily_usage",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identifier", "day"), name="unique_usage_identifier_day"
                    )
                ],
            },
        ),
    ]
