# Generated by Django 6.1 on 2026-08-31 13:56

import django_mongodb_backend.fields
from django.db import migrations, models

import downloads.models
import downloads.states


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFormat",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("format_id", models.CharField(max_length=128)),
                ("label", models.CharField(max_length=128)),
                ("extension", models.CharField(max_length=16)),
                ("kind", models.CharField(max_length=16)),
                ("height", models.PositiveIntegerField(null=True)),
                ("estimated_bytes", models.PositiveBigIntegerField(null=True)),
                ("selector", models.CharField(default="best", max_length=255)),
                ("playlist_item", models.PositiveIntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("public_token", models.CharField(max_length=96, unique=True)),
                ("owner_id", models.CharField(max_length=64)),
                ("fingerprint_id", models.CharField(max_length=64)),
                ("ip_id", models.CharField(max_length=64)),
                ("identity_key_version", models.PositiveSmallIntegerField(default=0)),
                ("source_url", models.URLField(max_length=2048)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("thumbnail_url", models.URLField(blank=True, max_length=2048)),
                ("duration_seconds", models.PositiveIntegerField(null=True)),
                (
                    "formats",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        default=list, embedded_model="downloads.storedformat"
                    ),
                ),
                ("resolver_context", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("inspection_queued", "inspection_queued"),
                            ("inspecting", "inspecting"),
                            ("ready", "ready"),
                            ("download_queued", "download_queued"),
                            ("downloading", "downloading"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                            ("blocked", "blocked"),
                            ("expired", "expired"),
                        ],
                        default=downloads.states.TaskState["INSPECTION_QUEUED"],
                        max_length=32,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("selected_format_id", models.CharField(blank=True, max_length=128)),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_detail", models.TextField(blank=True)),
                ("task_directory", models.CharField(blank=True, max_length=512)),
                ("output_file", models.CharField(blank=True, max_length=512)),
                ("output_size", models.PositiveBigIntegerField(default=0)),
                ("expires_at", models.DateTimeField(default=downloads.models.default_expiry)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "download_tasks",
                "indexes": [
                    models.Index(fields=["owner_id", "-created_at"], name="task_owner_created"),
                    models.Index(fields=["state", "updated_at"], name="task_state_updated"),
                    models.Index(fields=["expires_at"], name="task_expiry"),
                ],
            },
        ),
    ]
